apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-nodejs-app
spec:
  inputs:
    resources:
      - name: input-ui-source
        type: git
    params:
      - name: VERSION
        description: The version of the nodejs
        default: '10'
        type: string
  steps:
    - name: yarn-build-app
      image: 'registry.access.redhat.com/rhscl/nodejs-$(inputs.params.VERSION)-rhel7'
      workingDir: /workspace/input-ui-source
      command: ["/bin/bash", "-c"]

      args:
        - |-
          echo "install yarn"
          npm install -g yarn
          yarn install

          # use default service name for the fuse backend
          BACKEND_URL="http://nfuse:8080/services/app/expenses"
          echo "backEndUrl=$BACKEND_URL"
          # set backend url for redirects
          # set nginx proxy pass url
          sed -ri  "s|proxy_pass.*|proxy_pass $BACKEND_URL;|g" ./nginx.conf
          echo "build for prod"
          yarn install
          yarn build
          #copy web server config
          cp -r ./nginx.conf   ./build


    - name: deploy-app
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/input-ui-source
      command: ["/bin/bash", "-c"]

      args:
        - |-
          cd build
          ls -lisa
          echo "delete previous deployments if exist"
          oc delete  all --selector=app=nodejs-gui --ignore-not-found

          oc new-app --name=nodejs-gui --image-stream=openshift/nginx:1.16 --binary=true
          oc start-build nodejs-gui --from-dir .
          oc expose svc nodejs-gui





