---
apiVersion: build.rhone.io/v1
contributors:
    - email: nikolaj@majorov.biz
      name: Nikolaj Majorov
interpreter-version: lts
language: node_js
name: expenses-ui
version: 0.1.0
scripts:
    - preBuild: 'deno run build'
