---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: buildah-build-my-repo
spec:
    taskRef:
      name: buildah
    params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/nm-demo/gui:latest
      - name: TLSVERIFY
        value: false
      - name: DOCKERFILE
        value: Dockerfile.gen
      - name: SKIP_PUSH
        value: true    
    workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: ui-source-pvc