apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-nodejs-app
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: VERSION
        description: The version of the nodejs
        default: '10'
        type: string
  steps:
    - name: yarn-build-app
      image: 'registry.access.redhat.com/rhscl/nodejs-$(inputs.params.VERSION)-rhel7'
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      volumeMounts:
        #- name: varlibcontainers
        #  mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
      args:
        - |-
          echo "install yarn"
          npm install -g yarn
          yarn install

          # use default service name for the fuse backend
          BACKEND_URL="http://nfuse:8080/services/app/expenses"
          echo "backEndUrl=$BACKEND_URL"
          # set backend url with redirects
          # set react url just to api - nginx will handle the rest
          sed -ri  "s|=(.*)|= \"/api\";|g" src/utils/backendUrl.ts
          # set nginx proxy pass url
          sed -ri  "s|proxy_pass.*|proxy_pass $BACKEND_URL;|g" ./nginx.conf
          echo "build for prod"
          yarn install
          yarn build
          #copy web server config
          cp -r ./nginx.conf   ./build


    - name: deploy-app
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
      args:
        - |-
          cd build
          oc get deployment.apps/nodejs-gui
          if [[ $? -ne 0 ]]
             then
                #TODO: add params in task
                oc new-app nodejs-gui
                oc new-build --image-stream=nginx  --binary=true --name=nodejs-gui
                oc start-build nodejs-gui --from-dir=. --follow
                oc expose svc nodejs-gui
             else
                echo "Application already exists. trigger new s2i nginx build"
                oc start-build nodejs-gui --from-dir=. --follow
          fi

  volumes:
    - name: gen-source
      emptyDir: {}
