# run pipeline on master branch
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: expenses-webui-react17
spec:
  pipelineRef:
    name: build-expenses-web-ui
  params:
    - name: GIT_URL
      value: 'https://github.com/nmajorov/expenses-web-ui.git'
    - name: GIT_REVISION
      value: "react17"
    - name: SSO_URL
      value: 'http://sso-test-nm-demo.apps-crc.testing/auth'
    - name: BACKEND_URL
      value: 'http://expenses-backend-quarkus-nm-demo.apps-crc.testing'
  resources:
    - name: ui-image
      resourceRef:
        name: ui-image
  workspaces:
    - name: ui-workspace
      persistentVolumeClaim:
        claimName: ui-source-pvc
