---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-expenses-web-ui
spec:
  params:
    - name: GIT_URL
      description: "git url of client"
      default: https://github.com/nmajorov/expenses-web-ui.git
    - name: GIT_REVISION
      default: master
    - name: SSO_URL
      default: http://sso-test:8080/auth/
    - name: ui-image
      default: "image-registry.openshift-image-registry.svc:5000/nm-demo/gui:latest"

  workspaces:
    - name: ui-workspace
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task.

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: ui-workspace
    - name: test
      taskRef:
        name: test-nodejs-app
      runAfter:
        - clone
      workspaces:
        - name: input
          workspace: ui-workspace
    - name: build-and-deploy
      taskRef:
        name: deploy-nodejs-app
      params:
        - name: sso-url
          value: $(params.SSO_URL)
      runAfter:
        - test
      workspaces:
        - name: input
          workspace: ui-workspace

