apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: nodejs-pipeline-listener
  name: node-app-pipeline-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-nodejs-pipeline-listener