---
# test build of image separately
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-build-ui-image
spec:
  taskRef:
    name: webapp-build-runtime
  resources:
    outputs:
      - name: ui-image
        resourceRef:
          name: ui-image
  workspaces:
    - name: input
      persistentVolumeClaim:
        claimName: ui-source-pvc
