
export enum ActionKeys  {
    ADD_EXPENSE = "ADD_EXPENSE",
    REMOVE_EXPENSE = "REMOVE_EXPENSE",
    FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS",
    FETCH_ONE_EXPENSE =  "FETCH_ONE_EXPENSE",
    IS_FETCHING = "IS_FETCHING",
    FETCHING_IS_DONE="FETCHING_IS_DONE",
    SHOW_DELETE_DIALOG =  "SHOW_DELETE_DIALOG",
    REMOVE_MESSAGE = "REMOVE_MESSAGE",
    ADD_ERROR = "ADD_ERROR",
    SHOW_MESSAGE = "SHOW_MESSAGE",
    DO_SSO_LOGIN=  "DO_SSO_LOGIN",
    USER_PROFILE_LOADED=  "USER_PROFILE_LOADED",

    SSO_INITIALIZED =  "SSO_INITIALIZED"
    //CANCEL_FETCHING=  "CANCEL_FETCHING",
}
