
export enum ActionKeys  {
    ADD_EXPENSE = "ADD_EXPENSE",
    REMOVE_EXPENSE = "REMOVE_EXPENSE",
    FETCH_EXPENSES = "FETCH_EXPENSES",
    FETCH_ONE_EXPENSE=  "FETCH_ONE_EXPENSE",
    SHOW_DELETE_DIALOG =  "SHOW_DELETE_DIALOG",
    CLEAR_ERROR = "CLEAR_ERROR",
    ADD_ERROR = "ADD_ERROR",
    SHOW_ERROR = "SHOW_ERROR",
    DO_SSO_LOGIN=  "DO_SSO_LOGIN",
    SSO_INITIALIZED =  "SSO_INITIALIZED"
    //CANCEL_FETCHING=  "CANCEL_FETCHING",
}
