const constants = {
    ADD_PROJECT : "ADD_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
    LIST_PROJECT :"LIST_PROJECT",
    FETCH_PROJECTS: "FETCH_PROJECTS",
    FETCH_ONE_PROJECT: "FETCH_PROJECT",
    FETCH_BUILDS: "FETCH_BUILDS",
    GET_VERSION : "GET_VERSION",
    CLEAR_ERROR:"CLEAR_ERROR",
    ADD_ERROR:"ADD_ERROR",
    SHOW_ERROR: "SHOW_ERROR",
    SHOW_VERSION: "SHOW_VERSION",
    HIDE_VERSION: "HIDE_VERSION",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    START_BUILD_OK: "START_BUILD_OK"
}

export default constants;