const constants = {
    ADD_EXPENSE : "ADD_PROJECT",
    REMOVE_EXPENSE: "REMOVE_PROJECT",
    FETCH_EXPENSES: "FETCH_PROJECTS",
    CLEAR_ERROR:"CLEAR_ERROR",
    ADD_ERROR:"ADD_ERROR",
    SHOW_ERROR: "SHOW_ERROR"
    //CANCEL_FETCHING: "CANCEL_FETCHING",
}

export default constants;